/** Generated by scripts/gen-migrations.ts. Append only. */
export const migrationManifest: readonly {
	readonly ordinal: number;
	readonly id: string;
	readonly sha256: string;
}[] = [
	{
		ordinal: 1,
		id: "infrastructure-001",
		sha256: "d4cb9527d8ed6edca77f864b17e2d6a36d3aedc852fb56dcaf70aee8cded6c5e",
	},
	{
		ordinal: 2,
		id: "identity-001",
		sha256: "3fe776557fb6468ad5deabc0785192b803d4855487d1f197cba9bd3083353c0d",
	},
	{
		ordinal: 3,
		id: "lifecycle-001",
		sha256: "0e4c9d1a0087ac53e8a70a17689011bb6141083a177ab6dc9c4ebbcaf042b9c3",
	},
	{
		ordinal: 4,
		id: "assertions-001",
		sha256: "5ec1befcbdaa9c0d6ed06952c01961fb23f939a9d056315ee3e9efa7d65a4872",
	},
	{
		ordinal: 5,
		id: "projection-001",
		sha256: "76ace9cdb6ab41e991650cdc3515f8f04d13100cf807ba37200b90b4c18b2ed8",
	},
	{
		ordinal: 6,
		id: "scenarios-001",
		sha256: "12f13a4665702f5b8e3b79dfa3269e1f6634080a333d3525d44eb711caa2b75c",
	},
	{
		ordinal: 7,
		id: "extraction-001",
		sha256: "ba7dfc107888e1f47465cf42e3409b784bf255fbaf7e32db808125613e4b1a58",
	},
];
