/**
 * Pins migration hashes. Run `bun scripts/gen-migrations.ts` ONLY when adding a
 * new migration; a released descriptor must never change (tests fail if it does).
 * Writes: the sha256 literal in each descriptor file, migrations/manifest.ts,
 * spec/schema-v1.md (DDL listing).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { migrationDescriptors } from "../src/infrastructure/sqlite/migrations/index.ts";
import { migrationManifest } from "../src/infrastructure/sqlite/migrations/manifest.ts";
import { walk } from "./files.ts";
import { planPins } from "./migration-pin.ts";

const root = resolve(import.meta.dir, "..");
const allowUnreleased = process.argv.includes("--allow-unreleased");

/** Finds the file that declares each descriptor id (no naming guesses). */
const candidates = [
	...walk(resolve(root, "src/domains")).filter((f) =>
		/\/repository\/migrations\/[^/]+\.ts$/.test(f),
	),
	...walk(resolve(root, "src/infrastructure/sqlite/migrations")).filter((f) =>
		f.endsWith("schema-info.ts"),
	),
];
const fileOf = (id: string) => {
	const matches = candidates.filter((f) =>
		readFileSync(f, "utf8").includes(`id: "${id}"`),
	);
	if (matches.length !== 1)
		throw new Error(`cannot resolve the source file of ${id}`);
	return matches[0]!;
};

const plan = planPins(migrationManifest, migrationDescriptors, allowUnreleased);
if (plan.errors.length > 0) {
	console.error(plan.errors.join("\n"));
	console.error(
		"Refusing to change a released migration. Use --allow-unreleased only before any release.",
	);
	process.exit(1);
}
const manifest = plan.manifest;
for (const entry of manifest) {
	if (!plan.fresh.includes(entry.id)) continue;
	const path = fileOf(entry.id);
	const text = readFileSync(path, "utf8");
	writeFileSync(
		path,
		text.replace(/sha256: "[0-9a-f]{64}"/, `sha256: "${entry.sha256}"`),
	);
}
writeFileSync(
	resolve(root, "src/infrastructure/sqlite/migrations/manifest.ts"),
	`/** Generated by scripts/gen-migrations.ts. Append only. */
export const migrationManifest: readonly {
	readonly ordinal: number;
	readonly id: string;
	readonly sha256: string;
}[] = ${JSON.stringify(manifest, undefined, "\t")};
`,
);
const retention: Record<string, string> = {
	world_schema_info: "retained (schema metadata, no business data)",
	world_entity: "DELETE row on forget",
	world_alias: "DELETE row on forget",
	world_identity_event: "DELETE row on forget",
	world_assertion: "DELETE row on forget",
	world_assertion_head: "DELETE row on forget",
	world_transition: "DELETE row on forget",
	world_evidence: "DELETE row on forget",
	world_assertion_input: "DELETE row on forget",
	world_current: "DELETE row on forget (projection rebuilt)",
	world_edge: "DELETE row on forget (projection rebuilt)",
	world_scope_epoch: "retained (counter + digest of material set, no content)",
	world_prediction: "DELETE row on forget",
	world_outcome: "DELETE row on forget",
	world_inbox: "DELETE row on forget (pending events too)",
	world_input_manifest: "DELETE row on forget",
	world_manifest_dependency: "DELETE row on forget",
	world_checkpoint: "retained (opaque cursors only)",
	world_tombstone: "retained (kind/id/forget_id/reason enum only)",
	world_forget_operation: "retained (progress state only)",
	world_forget_target: "retained until complete (kind/id/revision only)",
	world_scope_gate: "retained",
	world_operation: "retained (digest + receipt ref; no payload body)",
};
const owner = (id: string) => id.replace(/-\d+$/, "");
let doc = `# World SQLite schema v1

Generated by \`scripts/gen-migrations.ts\` from the immutable migration
descriptors. Do not edit by hand; \`test/sqlite/schema-design.test.ts\` fails when
this file and the descriptors diverge. Contract: [C7](plan/contracts.md).

Rules fixed by the DDL: every table has NOT NULL \`principal\`/\`scope_key\`
as the first key columns; revisions are \`>= 1\`; lifecycle/origin/kind/relation
are CHECK enums; composite FKs stay inside one owner and include the Scope;
there are no cross-domain FKs or JOINs; tables are STRICT; all values are
bound by the repositories. \`payload_json\` holds canonical JSON owned by the
table's domain and is never copied to another table. Source/state reverse
lookups (\`source_key\`) are indexed with the Scope first.

Migration order (ordinal, id, sha256):

${manifest.map((m) => `- ${m.ordinal}. \`${m.id}\` \`${m.sha256}\``).join("\n")}

`;
for (const descriptor of migrationDescriptors) {
	doc += `## ${owner(descriptor.id)} (${descriptor.id})\n\n\`\`\`sql\n${descriptor.sql.trim()}\n\`\`\`\n\n`;
	const tables = [...descriptor.sql.matchAll(/CREATE TABLE (\w+)/g)].map(
		(m) => m[1]!,
	);
	doc += "| table | on forget |\n|---|---|\n";
	for (const table of tables) doc += `| ${table} | ${retention[table]} |\n`;
	doc += "\n";
}
writeFileSync(resolve(root, "spec/schema-v1.md"), doc);
console.log(`pinned ${manifest.length} migrations`);
